ARG BASE_PREFIX
ARG BASE_IMAGE_TAG
FROM neuvector/${BASE_PREFIX}manager_base:${BASE_IMAGE_TAG}

COPY stage /

RUN adduser -S manager
USER manager

ENTRYPOINT ["java", "-Xms256m", "-Xmx2048m", "-Djdk.tls.rejectClientInitiatedRenegotiation=true", "-jar", "/usr/local/bin/admin-assembly-1.0.jar"]
